apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: walmart-netsec
data:
  ENVIRONMENT: "production"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "network_security_automation"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  LOG_LEVEL: "INFO"
