apiVersion: v1
kind: Service
metadata:
  name: netsec-automation
  namespace: walmart-netsec
spec:
  selector:
    app: netsec-automation
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer
